---
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libxml2-utils
sudo: false
node_js:
  - "6.3"
branches:
  only:
    - master
    - /^TF-.*/
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
script:
  xmllint --noout metadata/*.xml
  npm test
