---
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libxml2-utils
sudo: false
node_js:
  - lts/*
branches:
  only:
    - master
    - /^TF-.*/
    - /^TF_.*/
    - /^DSP*/
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
script:
  - xmllint --noout metadata/*.xml
  - npm test -- --reporter dot
